server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:RestaurantDB
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate: create
    show-sql: true
  h2:
    console:
      enabled: true
    path: /h2-console